apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eurcliservice.name }}
  labels:
    app: {{ .Values.eurcliservice.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.eurcliservice.containerPort }}
  selector:
    app: {{ .Values.eurcliservice.name }}