apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefilepv
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - "ReadWriteMany"
  azureFile:
    secretName: azure-secret
    shareName: k8spv
    readOnly: false