apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eurekaclient
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eurekaclient
    spec:
      containers:
      - name: eurekaclient
        image: maninderjit/eurcli:0.1
        ports:
        - containerPort: 8090
        env:
        - name: EUREKA_SERVICE_URL 
          value: eurekaservice:8761
      imagePullSecrets:
      - name: acssecret