apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: maninderjit/eurser:0.1
        ports:
        - containerPort: 8761
      imagePullSecrets:
      - name: acssecret
